apiVersion: v1
kind: Service
metadata:
  name: ip-anonymization-service
  namespace: ti-dcp
spec:
  ports:
  - port: 8100
    targetPort: 8100
  selector:
    app: ip-anonymization
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-anonymization
  namespace: ti-dcp
spec:
  selector:
    matchLabels:
      app: ip-anonymization
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ip-anonymization
    spec:
      containers:
      - name: ip-anonymization
        image: 10.101.10.244:5000/ip-anonymization:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
          hostPort: 8100
          protocol: TCP
        env:
          - name: DB_INSTANCE
            value: redis
          - name: DB_HOST
            value: redis-service.ti-dcp
          - name: DB_PORT
            value: "6379"
          - name: DB_USERNAME
            value: ""
          - name: DB_PASSWORD
            value: ""
          - name: DB_NAME
            value: "0"
