apiVersion: v1
kind: Service
metadata:
  name: redis-insight-service
  namespace: ti-dcp
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: redis-insight
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
  namespace: ti-dcp
  labels:
    app: redis-insight
spec:
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
      - name:  redis-insight
        image: redislabs/redisinsight:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1001
        volumeMounts:
        - name: db
          mountPath: /db
        ports:
        - containerPort: 8001
          hostPort: 8001
          protocol: TCP
      volumes:
      - name: db
        hostPath:
          path: /media/palantir-nfs/SPH/volumes/redis-insight
